#+TITLE: Doom Emacs Config
#+PROPERTY: header-args :tangle config.el

* Table of Contents :toc:
- [[#ui][UI]]
  - [[#setting-the-font][Setting the font]]
  - [[#setting-the-theme][Setting the Theme]]
- [[#org-mode][Org Mode]]
  - [[#org-folded-state-icon][Org Folded State Icon]]
  - [[#org-directory][Org Directory]]
  - [[#org-bullets][Org Bullets]]
- [[#org-agenda][Org Agenda]]
  - [[#agenda-files][Agenda Files]]
  - [[#agenda-log][Agenda Log]]
- [[#custom-key-bindings][Custom key bindings]]
  - [[#auto-comment-lines][Auto comment lines]]
- [[#cursor][Cursor]]
- [[#dashboard][DASHBOARD]]
  - [[#configuring-dashboard][Configuring Dashboard]]
  - [[#dashboard-in-emacsclient][Dashboard in Emacsclient]]
- [[#modeline][MODELINE]]

* UI
** Setting the font
Setting the font so emacs is easily readable.
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Fira Code Retina" :size 20 :weight 'regular)
      doom-variable-pitch-font (font-spec :family "sans" :size 13))
#+end_src

** Setting the Theme
Setting the theme to make emacs cool.
#+begin_src emacs-lisp
(setq doom-theme 'doom-one)
#+end_src

* Org Mode
Settings for Org Mode
** Org Folded State Icon
This settings the icon to display when the org headings are in a folded state.
#+begin_src emacs-lisp
(setq org-ellipsis " ▼ ")
#+end_src
** Org Directory
Location to my Org files directory.
#+begin_src emacs-lisp
(setq org-directory "~/Desktop/Org/")
#+end_src
** Org Bullets
Enabling org bullets and setting custom font size for all of them.
#+begin_src emacs-lisp
(add-hook 'org-mode-hook #'org-bullets-mode)
(setq inhibit-compacting-font-caches t)
(custom-set-faces
  '(org-level-1 ((t (:inherit outline-1 :height 1.4))))
  '(org-level-2 ((t (:inherit outline-2 :height 1.3))))
  '(org-level-3 ((t (:inherit outline-3 :height 1.2))))
  '(org-level-4 ((t (:inherit outline-4 :height 1.1))))
  '(org-level-5 ((t (:inherit outline-5 :height 1.0))))
)
#+end_src

#+RESULTS:

* Org Agenda
** Agenda Files
The Location to my Agenda Org files.
#+begin_src emacs-lisp
(setq org-agenda-files
      '("~/Desktop/Org/Agenda/Tasks.org"
        "~/Desktop/Org/Agenda/Urgent.org"
        "~/Desktop/Org/Agenda/Events.org"))
#+end_src
** Agenda Log
This setting makes Agenda more detaied.
#+begin_src emacs-lisp
(setq org-agenda-start-with-log-mode t)
(setq org-log-done 'time)
(setq org-log-into-drawer t)
#+end_src

* Custom key bindings
Some of the keybindings of doom emacs do not suit my taste so i set a few custom ones.
** Auto comment lines
Comment and uncommenting lines is one of the most used features so I set it to a easily accesible binding.
#+begin_src emacs-lisp
(map!
 :leader
 :desc "Comment line"
 "TAB TAB" #'comment-line)
#+end_src
    
* Cursor
Cursor is the most important feature when coding. So i made to be a box all the time.
#+begin_src emacs-lisp
(setq evil-motion-state-cursor 'box)  ; █
(setq evil-visual-state-cursor 'box)  ; █
(setq evil-normal-state-cursor 'box)  ; █
(setq evil-insert-state-cursor 'box)  ; █
(setq evil-emacs-state-cursor  'hbar) ; _
#+end_src

* DASHBOARD
Emacs Dashboard is an extensible startup screen showing you recent files, bookmarks, agenda items and an Emacs banner.

** Configuring Dashboard
#+begin_src emacs-lisp
(use-package dashboard
  :init      ;; tweak dashboard config before loading it
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
  (setq dashboard-startup-banner "~/.doom.d/doom-emacs-dash.png")  ;; use custom image as banner
  (setq dashboard-center-content nil) ;; set to 't' for centered content
  (setq dashboard-items '((recents . 5)
                          (agenda . 5 )
                          (bookmarks . 5)
                          (projects . 5)))
  :config
  (dashboard-setup-startup-hook)
  (dashboard-modify-heading-icons '((recents . "file-text")
                                    (bookmarks . "book"))))
#+end_src

** Dashboard in Emacsclient
This setting ensures that emacsclient always opens on *dashboard* rather than *scratch*. doesn't work at the moment.
#+begin_src emacs-lisp
(setq doom-fallback-buffer "*dashboard*")
#+end_src

* MODELINE
The modeline is the bottom status bar that appears in Emacs windows.  For more information on what is available to configure in the Doom modeline, check out:
https://github.com/seagle0128/doom-modeline

#+begin_src emacs-lisp
(set-face-attribute 'mode-line nil :font "Ubuntu Mono-13")
(setq doom-modeline-height 30     ;; sets modeline height
      doom-modeline-bar-width 5)  ;; sets right bar width
#+end_src
